# Generated by Django 4.2.27 on 2026-02-01 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("posts", "0001_initial"),
        ("karma", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="karmatransaction",
            name="related_like",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="posts.like"
            ),
        ),
    ]
