# Generated by Django 4.2.27 on 2026-02-01 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("karma", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="karmatransaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="karma_transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="karmatransaction",
            index=models.Index(
                fields=["user", "-created_at"], name="karma_karma_user_id_8fed0f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="karmatransaction",
            index=models.Index(
                fields=["-created_at"], name="karma_karma_created_b50bec_idx"
            ),
        ),
    ]
