# Generated by Django 4.2.27 on 2026-02-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_anonymous",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
